WITH RECURSIVE HOURS AS
(
    SELECT 0 as HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)

SELECT H.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM HOURS AS H
LEFT OUTER JOIN
    (SELECT HOUR(DATETIME) AS HOUR, ANIMAL_ID
    FROM ANIMAL_OUTS) AS A
    ON H.HOUR = A.HOUR
GROUP BY
    H.HOUR